= Curriculum vitae Cristian Romero Matesanz

== Personal Data

[frame=all,grid=none, cols="1s,1"]
|===

| Name | Cristian

| Surname | Romero

| Birth's date | 20th Julio 1981, Madrid

| Nationality | Spain

| Mail | cristianprofile@gmail.com

| Gender | Male

|===

== Profile

I am an enthusiastic programmer, in 2 words I am an eternal student.
14 years using a lot of languages, but specialized in JAVA SPRING
and every Frameworks around it. I love Kotlin language because
it has a lot of features that make my life as programmer easier. (I hate null pointer exception)

Interested in web, mobile, testing new databases needed to be able to resolve
new problems with a better approach than old relational database:

Elasticsearch, Redis, Mongo, Neo4j, Influxdb.

This last year I am learning the complex word :microservices solutions.I am learning new ways of work with a complex
distribution system. Actually I am trying to learn how to use new Kafka solutionto be able to create event driven microservices and studying
new ways to create application improving startup time like Micronaut (Spring boot is improving startup time but it is too slow yet)

<<<

== Education

[frame=none,grid=none, cols="1s,1,2a"]
|===

| 2000-2005
|
| *Engineer’s Degree Computer Science Engineering* +
_Universidad Carlos III Madrid_


|===

== Profile Technology overview

*Frameworks* Spring Boot 2, Spring 5 (mvc, core, data security etc ...) , Vertx, Micronaut, unit and integration test (Mockito, PowerMock, Postman).

*Programming language* Java 11(backend), Kotlin (backend), Groovy (Jenkins file and Gradle)

*Ide* Intellij lover (I'm a pro licence owner).I love to pay tools that make my programmer life easier.

*Build automation tool* Maven/Gradle

*Preferred SO* Macos with unix (the best from windows and similar commands in terminal to Linux)

*Preferred Computer* Macbook pro of course :)

*CI* Gitlab CI / Jenkins 2

*Issues Management* Jira or Gitlab/Github issues (the same as Spring team)

*Relational Databases* Oracle, Mysql, Postgresql

*Non relational Databases* Elasticsearch (Elk/search engine using aggregates), Redis (Cache),
Neo4j (graph database), Influxdb (time serie database analystics purpose), mongoDb(documents)

*Container/deployment* Docker and Kubernetes (only used and configured as developer. I am not a devops profile)

*"Real time" Analytics* Grafana/Kibana

== Professional Experience

[frame=none,grid=none, cols="1s,1,2a"]
|===

| 2017-Present
|
|  *Senior Backend developer/Architect (Mymoid)* +


*Job Description:* Backend Team Leader of payment gateway product solution PCI compliance connecting brands with its customers.
Api Rest, Elk infrastructure, Analytics solution (Elasticsearch),Git .

*Tools* Spring Boot,Spring Data,Spring mvc, Spring Batch,Java 8/Kotlin,Maven, unit and integration test (Mockito, PowerMock, Postman),
Jenkins 2 (Groovy pipelines), Mysql, Elasticsearch, Redis, Git


| 2015-2017
|
|  *Architect Leader/Functional Analyst (Adesis Netlife/GFT)* +


*Job Description:* Functional Analyst defining multi channel rest services BBVA Continental Perú.
                   Architect Leader defining product solution using elasticsearch as primary databases (Bankia)

*Tools* Spring Boot,Spring Data, Spring mvc, Java,Maven, unit and integration test (Mockito, PowerMock, Postman), Elasticsearch, Java 7,Git


| 2014-2015
|
|  *Architect (Entelgy)* +


*Job Description:*
Architect Leader in Telefonica (Telco 3.0 project).Defining how to external programmers  create applications using Jenkins as CI.

*Tools* Spring,Spring Data, Spring mvc, Java,Maven, unit and integration test (Mockito, PowerMock, Postman),Jenkins,Git.


| 2013-2014
|
|  *Architect (Wul4)* +


*Job Description:*
Architect Leader/programmer in Redsys designing new disruptive wallet product (Iupay) with Spanish Banks like Banco Popular,Santander,
Bankia,Sabadell,BBVA (www.iupay.es).

*Tools* Spring,Spring Data,Java,Maven, Spring mvc, unit and integration test (Mockito, PowerMock),Svn.


| 2012-2013
|
|  *Architect (Equifax)* +


*Job Description:*
Senior programmer in Equifax designing/programming maven archetypes for several products inside company. Prototypes were
created with Spring Roo 1. One of the main product were migrate an old tool to a platform using sockets created with
Spring integration using several integration patterns.

*Tools* Spring,Spring Data,Java,Maven, Spring mvc, Spring Integration, Jenkins 1, unit and integration test (Mockito, PowerMock),Svn.



| 2011-2012
|
|  *Analyst/programmer (Ministerio territorial)* +


*Job Description:*
Senior programmer in Ministerio territorial designing/programming several applications inside company using Alfresco
as Document store solution. The backend solution was developed using Spring and fronted solution using Jsf with Primefaces

*Tools* Spring,Spring Data,Java,Maven, Spring mvc, Jsf, unit and integration test,Svn


| 2009-2011
|
|  *Analyst/programmer (Profile Software Services)* +


*Job Description:*
Senior programmer in Idealista designing/programming batch application solution for large customers.
Senior programmer in Mutua Madrileña designing/programming j2ee tools using IBM portal (Portlets)

*Tools* Spring,Spring Data,Java,Maven, html, css, javscript, jquery, Rad, Svn


| 2007-2009
|
|  *Analyst/programmer (Union Fenosa)* +


*Job Description:*
Junior programmer in Union Fenosa designing/programming Union Fenosa portal (websphere portal IBM)


*Tools* Java,Ant, html, css, javscript, jquery, Rad, Svn, Jsf


| 2006-2007
|
|  *Analyst/programmer (Vodafone)* +


*Job Description:*
Junior programmer in Union Fenosa designing/programming integration process using Business work (Tibco)
Tester of canal online vodafone portal solution


*Tools* Java,Ant,Tibco, Business work, Svn

|===


<<<

== Projects
.As developer Hosted on github
* https://github.com/cristianprofile

.As teacher: Hosted on slideshare
* https://es.slideshare.net/cristianromeromatesanz

.Helping software community: Hosted on stackoverflow
* https://stackoverflow.com/users/4615649/cristian-romero-matesanz

== Interests & Additional Information
I love all kind of music, in special electronic music (it is one of my hobbies).